name: Complete workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - run: git fetch --prune --unshallow

            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}

            - name: Install dependencies
              run: yarn --fronzen-lockfile

            - name: Run the tests
              run: yarn test

            - name: Send tests to Coveralls
              run: yarn test:coveralls
              with:
              github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run Lint
              run: yarn lint
